import {
  Component,
  ElementRef,
  HostBinding,
  Input,
  OnInit,
  SecurityContext,
  TemplateRef,
  ViewChild
} from '@angular/core';
import {DomSanitizer} from '@angular/platform-browser';
import {CaTextEditorsManagerState} from '../../state/ca-text-editors-manager.state';
import {Observable} from 'rxjs';
import {CaTextEditorImageLoader} from '../../model/ca-text-editor-image.class';
import {CaTextEditorElementDirective} from '../../model/ca-text-editor-element.directive';
import {ClStringHelper} from '@monorepo/core-lib';
import {FlResizeEvent} from '@monorepo/front-core-lib';

/**
 * Figure component in text editor generated by {@link CaTextEditorFigureBlot}
 */
@Component({
  selector: 'ca-text-editor-figure',
  templateUrl: './ca-text-editor-figure.component.html',
  styleUrls: ['./ca-text-editor-figure.component.scss']
})
export class CaTextEditorFigureComponent extends CaTextEditorElementDirective implements OnInit {

  @HostBinding('attr.filename')
  @Input() filename: string;

  @Input() naturalWidth: string;

  @Input() naturalHeight: string;

  @HostBinding('attr.width')
  @Input() width: string;

  @HostBinding('attr.height')
  @Input() height: string;

  @HostBinding('attr.image-title')
  @Input() imageTitle: string;

  @HostBinding('attr.caption')
  @Input() caption: string;

  @ViewChild('figure') figure: ElementRef<HTMLElement>;

  @ViewChild('templatePortalContent') templatePortalContent: TemplateRef<unknown>;

  imageWidth: number;
  imageHeight: number;

  sanitizedUrl: string;

  private config: CaTextEditorImageLoader;

  disabled$: Observable<boolean>;

  init = false;

  constructor(private sanitizer: DomSanitizer,
              elementRef: ElementRef<HTMLElement>,
              managersState: CaTextEditorsManagerState) {
    super(elementRef, managersState);
    this.config = this.state.config as any;
  }

  ngOnInit(): void {
    if (ClStringHelper.isHttpLink(this.filename)) {
      this.sanitizedUrl = this.filename;
    } else {
      this.sanitizedUrl = this.sanitizer.sanitize(SecurityContext.URL, this.config.getImageUrl(this.filename));
    }
    this.disabled$ = this.getDisabled$();
    // let the parent have its width
    setTimeout(() => this.initSize(), 0);
  }


  private initSize(): void {
    const width = parseFloat(this.width);
    const height = parseFloat(this.height);
    const parentWidth = this.elementRef.nativeElement.clientWidth;
    // if the image is larger than container, resize it
    if (parentWidth > 0 && width > parentWidth) {
      this.imageWidth = parentWidth;
      this.imageHeight = ((parentWidth / width) * parseFloat(this.height));
    } else {
      this.imageWidth = width;
      this.imageHeight = height;
    }

    this.init = true;
  }

  onImageResize(resizeEvent: FlResizeEvent): void {
    this.width = resizeEvent.width + '';
    this.height = resizeEvent.height + '';
  }

}
