import { FlAdvancedSearchInput, FlSearchCriteria, FlSearchOperator } from './fl-search.class';
import { DateTime } from 'luxon';
import { ClDateHelper, ClHelpService, ClLuxonDateTimeTransform } from '@monorepo/core-lib';
import { FlEntity } from '../../../model/fl-entity.class';
import {
  FlDatasourceGetPageData,
  FlDatasourceSortCriteria
} from '../../../model/datasource/fl-datasource-paginated.class';
import { FlSortCriteria } from './fl-sort.class';

/**
 * Object used to convert an object attribute to a {@link FlSearchCriteria} to perform a advanced search
 */
export interface FlSearchAttributeCriteriaConverter<T = string> {
  /**
   * Name of the column that will be used in the {@link FlSearchCriteria}. Support '.' to go deeply in objects
   */
  key: string;

  /**
   * Operation to filters the data passed to the {@link FlSearchCriteria}
   * If a {@link FlSearchOperator} is provided, the value is used directly
   * If a function is provided the function is call with the value to get different
   * {@link FlSearchOperator} based on criteria value
   */
  operator: FlSearchOperator | ((value: T) => FlSearchOperator);

  /**
   * Optional method to convert the attribute value to the value needed by the advanced search
   * For example: only returning the id of an object for the search
   *
   * If not provided the attribute value is directly used and no conversion are performed
   * @param value value to convert
   */
  convertValue?: (value: T) => any;
}

/**
 * Function to convert a search object attribute to SearchCriteria[];
 *
 * The value of the function is the object value (usually value from form),
 * IT CAN BE NULL or EMPTY
 */
export type FlSearchAttributeFunctionCriteriaConverter<T> = (value ?: T) => FlSearchCriteria[];

/**
 * Type for describing a conversion from an object of type P to a list of criteria
 *
 * Each object key should define how to convert the object to SearchCriteria
 *
 * Each value define either
 * - information to convert to SearchCriteria (Using SearchAttributeCriteriaConverter)
 * - a function to directly convert object info to SearchCriteria[] (for specific cases)
 */
export type FlSearchFilterCriteriaConverter<T> = {
  [P in keyof T]: FlSearchAttributeCriteriaConverter<T[P]> | FlSearchAttributeFunctionCriteriaConverter<T[P]>;
};

/**
 * Converter for sorting criteria. The key is the column name use in mat-table, the value is the column name in the backend
 * The value can be an array if it implies a sort on multiple columns (like firstname and lastname for a user)
 */
export type FlSearchSortCriteriaConverter = Record<string, string | string[]>;

/**
 * Type for date group when using date interval to filter on same
 * date
 */
export class FlSearchDateInterval {

  @ClLuxonDateTimeTransform()
  from: DateTime;

  @ClLuxonDateTimeTransform()
  to: DateTime;
}

/**
 * Generic converter for Advanced Search
 */
export class FlSearchConverter {


  /**
   * Convert a {@link FlDatasourceGetPageData} usually used in a datasource to a {@link FlAdvancedSearchInput}
   * to trigger a search
   * @param data
   * @param filterConverter
   * @param sortConverter
   */
  public static convertDatasourceGetPageDataToSearchParams<T>(data: FlDatasourceGetPageData,
                                                              filterConverter: FlSearchFilterCriteriaConverter<T>,
                                                              sortConverter: FlSearchSortCriteriaConverter): FlAdvancedSearchInput {
    if (data == null) {
      return {
        filtersCriteria: [],
        sortsCriteria: []
      };
    }
    return {
      filtersCriteria: FlSearchConverter.convertObjectToSearchCriteriaList(data.filtersCriteria, filterConverter),
      sortsCriteria: FlSearchConverter.convertDatasourceGetPageSortToSearchSort(data.sortsCriteria, sortConverter)
    };
  }

  /**
   * Convert an object (usually generated by a form) to a list of {@link FlSearchCriteria}
   * to perform an advanced search.
   *
   * It loops through object attributes and convert it (if not null)
   * to a {@link FlSearchCriteria}
   * @param object object containing the filtering values
   * @param converter object used to convert objects attributes to {@link FlSearchCriteria}
   */
  public static convertObjectToSearchCriteriaList<T = Record<any, any>>(object: T,
                                                                        converter: FlSearchFilterCriteriaConverter<T>)
    : FlSearchCriteria[] {
    const criteria: FlSearchCriteria[] = [];

    if (object == null) return criteria;

    for (const key of Object.keys(object)) {
      const fieldValue: any = (object as any)[key];


      // handle specific convert as function
      // for SearchAttributeFunctionCriteriaConverter
      if (typeof (converter as any)[key] === 'function') {
        // call the function to get the criteria
        const newCriteria: FlSearchCriteria[] = (converter as any)[key](fieldValue);
        if (newCriteria != null) {
          criteria.push(...newCriteria);
        }
        continue;
      }

      const fieldConverter: FlSearchAttributeCriteriaConverter<T> = (converter as any)[key];

      // check if the convert for this field exists
      if (fieldConverter == null) {
        console.error('The convert for the field \'' + key + '\' does not exists. Skipping field');
        continue;
      }

      // get the operation
      let operator: FlSearchOperator;
      // if the operation is a function, call it
      if (typeof fieldConverter.operator === 'function') {
        operator = fieldConverter.operator(fieldValue);
      } else {
        // otherwise get the operation directly
        operator = fieldConverter.operator;
      }

      // get the value
      let value: any;
      // if a convert function exists, call it
      if (fieldConverter.convertValue != null) {
        value = fieldConverter.convertValue(fieldValue);
      } else {
        // get the value directly
        value = fieldValue;
      }

      // if the converted value is null or empty, skip
      if (ClHelpService.isNullOrEmpty(value)) {
        continue;
      }

      criteria.push({
        key: fieldConverter.key,
        operator: operator as any,
        value: value
      });

    }
    return criteria;
  }


  /**
   * Simple method to return the id of a {@link FlEntity}
   * @param object entity
   */
  public static getEntityId(object: FlEntity): string {
    return object?.id ?? null;
  }

  public static getCustomKey(key: string) {
    return (value ?: any): any => {
      if (value == null) {
        return null;
      }
      return value[key];
    };
  }

  /**
   * Simple method to convert a list of {@link FlEntity} to the list
   * of the ids
   * @param objects entities
   */
  public static getEntitiesId(objects: FlEntity[]): string[] {
    if (objects == null) return null;
    return objects.map(o => FlSearchConverter.getEntityId(o));
  }

  /**
   * Simple method to convert a Date to time
   * for the advanced search
   * @param date date to convert
   */
  public static convertDateToTime(date: Date): number {
    return date?.getTime() ?? null;
  }

  /**
   * Simple method to convert a DateTime to time
   * for the advanced search
   * @param date to convert
   */
  public static convertDateTimeToString(date: DateTime): string {
    return ClDateHelper.serializeDateTime(date);
  }

  /**
   * Simple method to convert a DateTime to time
   * for the advanced search
   * @param date to convert
   */
  public static convertDateToString(date: DateTime): string {
    return ClDateHelper.serializeDate(date);
  }


  /**
   * For advanced search, it convert a {@link FlSearchDateInterval} to SearchCriteria
   * depending on which interval is set
   * @param key column key
   */
  public static dateTimeInterval(key: string): FlSearchAttributeFunctionCriteriaConverter<FlSearchDateInterval> {
    return FlSearchConverter.convertDateInterval(key, FlSearchConverter.convertDateTimeToString);
  }

  /**
   * For advanced search, it convert a {@link FlSearchDateInterval} to SearchCriteria
   * depending on which interval is set
   * @param key column key
   */
  public static dateInterval(key: string): FlSearchAttributeFunctionCriteriaConverter<FlSearchDateInterval> {
    return FlSearchConverter.convertDateInterval(key, FlSearchConverter.convertDateToString);
  }

  private static convertDateInterval(key: string, dateConverter: (date: DateTime) => string):
    FlSearchAttributeFunctionCriteriaConverter<FlSearchDateInterval> {
    return (dates?: FlSearchDateInterval): FlSearchCriteria[] => {
      let criteria: FlSearchCriteria;
      // if the 2 dates are null
      if (dates == null || (dates.from == null && dates.to == null)) {
        return null;
      } else if (dates.to == null) {
        // if only the From date is filled
        criteria = {
          key: key,
          operator: 'GE',
          value: dateConverter(dates.from)
        };
      } else if (dates.from == null) {
        // if only the To date is filled
        criteria = {
          key: key,
          operator: 'LE',
          value: dateConverter(dates.to)
        };
      } else {
        // if both dates are filled
        criteria = {
          key: key,
          operator: 'BETWEEN',
          value: [dateConverter(dates.from), dateConverter(dates.to)]
        };
      }
      return [criteria];
    };
  }

  public static convertDatasourceGetPageSortToSearchSort(sortsCriteria: FlDatasourceSortCriteria[] | null,
                                                         converter: FlSearchSortCriteriaConverter): FlSortCriteria[] | null {
    if (sortsCriteria == null || converter == null) return null;
    const convertedSorts: FlSortCriteria[] = [];

    for (const sort of sortsCriteria) {
      const key = converter[sort.key];
      if (key == null) {
        console.error('The key \'' + sort.key + '\' does not exists in the sort converter. Skipping sort');
        continue;
      }

      const keys = ClHelpService.convertObjectOrArrayToArray(key);
      for (const k of keys) {
        convertedSorts.push({
          key: k,
          direction: sort.direction,
          nullManagement: 'LAST'
        });
      }
    }
    return convertedSorts;

  }

}

