import { Component, inject, OnDestroy, OnInit, Renderer2 } from '@angular/core';

import { ClTheme } from '@monorepo/core-lib';
import { RenderData, Streamlit } from 'streamlit-component-lib';
import { DcIframeToMainEventEmitter } from '../../core/iframe-event/dc-iframe-event-emitter.class';
import { DcMainToIframeEventListener } from '../../core/iframe-event/dc-iframe-event-listener.class';
import {
  dcGetIframeMessageHost,
  DcIframeEventAction,
  DcMainToIframeEvent,
} from '../../core/iframe-event/dc-iframe-event.class';
import { DcComponentData } from '../../core/model/dc-dynamic-component.class';

/**
 * This app is only used in production mode
 * This is the component that is generated by streamlit and run in the iframe
 * Its role is only to communicate with the gws_plugin that is running outside
 * the iframe, in the main streamlit app.
 * It sends a message to the parent to initialize the component
 * and listen to the messages from the parent to update the component value
 */
@Component({
  standalone: true,
  imports: [],
  selector: 'dc-root',
  templateUrl: './dc-iframe-message.component.html',
  styleUrl: './dc-iframe-message.component.scss',
})
export class DcIframeMessageComponent implements OnInit, OnDestroy {
  private renderer = inject(Renderer2);

  private iframeEventEmitter = new DcIframeToMainEventEmitter(dcGetIframeMessageHost());
  private parentEventListener: DcMainToIframeEventListener;

  private lastTimestamp: number = 0;

  ngOnInit(): void {
    this.parentEventListener = new DcMainToIframeEventListener(
      dcGetIframeMessageHost(),
      this.renderer,
      window
    );
    this.parentEventListener.listenToIframeEvents().subscribe((event) => this.onParentMessage(event));

    Streamlit.events.addEventListener(Streamlit.RENDER_EVENT, (event: Event) => {
      const customEvent: CustomEvent<RenderData> = event as CustomEvent<RenderData>;

      const data: DcComponentData = customEvent.detail.args;
      if (this.lastTimestamp === data.timestamp) {
        return; // avoid reloading the component if the timestamp is the same
      }

      this.lastTimestamp = data.timestamp;

      const clTheme: ClTheme =
        customEvent.detail.theme.base === 'dark' ? ClTheme.DARK_THEME : ClTheme.LIGHT_THEME;

      this.postEventMessage(data, clTheme);
    });

    Streamlit.setComponentReady();
    Streamlit.setFrameHeight(0);
  }

  private postEventMessage(config: DcComponentData, theme: ClTheme): void {
    // Send message to parent (Streamlit runs on port 8501)
    this.iframeEventEmitter.initComponent({
      componentData: config,
      theme: theme,
    });
  }

  private onParentMessage(data: DcMainToIframeEvent): void {
    switch (data.action) {
      case DcIframeEventAction.SET_COMPONENT_VALUE:
        Streamlit.setComponentValue(data.data);
        break;
      default:
        console.warn('Unknown action from parent:', data.action);
        break;
    }
  }

  // Clean up when component is destroyed
  ngOnDestroy(): void {
    this.parentEventListener?.destroy();
  }
}
