import { Component, Inject, OnInit } from '@angular/core';
import { LabFolder } from '../../../../model/entities/lab-folder.class';
import { MAT_DIALOG_DATA, MatDialogRef } from '@angular/material/dialog';
import { LabResourceService } from '../../../../entity-service/lab-resource.service';
import { LabScenarioService } from '../../../../entity-service/lab-scenario.service';
import { FormControl } from '@angular/forms';
import { FlSnackBarService } from '@monorepo/front-core-lib';
import { LabScenario } from '../../../../model/entities/lab-scenario.entity';
import { LabResource } from '../../../../model/entities/resource/lab-resource.entity';

export interface LabResourceUpdateFolderDialogInput {
  resourceId: string;
  scenario?: {
    id: string;
    title: string;
  };
  folder?: LabFolder;
}

export interface LabResourceUpdateFolderDialogOutput {
  folder?: LabFolder;
}

/**
 * Dialog to update the folder of a resource
 * If the resource was generated by an scenario, it updates the folder of the scenario if possible
 */
@Component({
  selector: 'lab-resource-update-folder-dialog',
  templateUrl: './lab-resource-update-folder-dialog.component.html',
  styleUrls: ['./lab-resource-update-folder-dialog.component.scss'],
})
export class LabResourceUpdateFolderDialogComponent implements OnInit {
  formControl: FormControl<LabFolder>;

  isLoading: boolean;

  constructor(
    @Inject(MAT_DIALOG_DATA) public data: LabResourceUpdateFolderDialogInput,
    private dialogRef: MatDialogRef<LabResourceUpdateFolderDialogComponent>,
    private resourceService: LabResourceService,
    private scenarioService: LabScenarioService,
    private snackBarService: FlSnackBarService
  ) {}

  ngOnInit(): void {
    this.formControl = new FormControl(this.data.folder);
  }

  get isUpdateResourceFolderMode(): boolean {
    return !this.data.scenario;
  }

  submit(): void {
    if (this.formControl.valid && !this.isLoading) {
      this.isLoading = true;

      const folderId = this.formControl.value?.id ?? null;
      if (this.isUpdateResourceFolderMode) {
        this.updateResourceFolder(folderId);
      } else {
        this.updateScenarioFolder(folderId);
      }
    }
  }

  private updateResourceFolder(folderId: string): void {
    this.resourceService.updateFolder(this.data.resourceId, folderId).subscribe({
      next: (resource) => this.updateResourceFolderSuccess(resource),
      error: () => (this.isLoading = false),
    });
  }

  private updateResourceFolderSuccess(resource: LabResource): void {
    this.snackBarService.openSuccessMessage({ text: 'biox.resource_folder_updated', translateText: true });
    this.closeDialog(resource.folder);
  }

  private updateScenarioFolder(folderId: string): void {
    this.scenarioService.updateFolder(this.data.scenario.id, folderId).subscribe({
      next: (scenario) => this.updateScenarioFolderSuccess(scenario),
      error: () => (this.isLoading = false),
    });
  }

  private updateScenarioFolderSuccess(scenario: LabScenario): void {
    this.snackBarService.openSuccessMessage({ text: 'biox.scenario_folder_updated', translateText: true });
    this.closeDialog(scenario.folder);
  }

  private closeDialog(folder: LabFolder): void {
    this.isLoading = false;
    this.dialogRef.close({ folder: folder } as LabResourceUpdateFolderDialogOutput);
  }
}
