import {Component, Inject, OnInit} from '@angular/core';
import {LabFolder} from '../../../../model/entities/lab-folder.class';
import {MAT_DIALOG_DATA, MatDialogRef} from '@angular/material/dialog';
import {LabResourceService} from '../../../../entity-service/lab-resource.service';
import {LabExperimentService} from '../../../../entity-service/lab-experiment.service';
import {FormControl} from '@angular/forms';
import {FlSnackBarService} from '@monorepo/front-core-lib';
import {LabExperiment} from '../../../../model/entities/lab-experiment.entity';
import {LabResource} from '../../../../model/entities/resource/lab-resource.entity';


export interface LabResourceUpdateFolderDialogInput {
  resourceId: string;
  experiment?: {
    id: string;
    title: string;
  };
  folder?: LabFolder;
}

export interface LabResourceUpdateFolderDialogOutput {
  folder?: LabFolder;
}

/**
 * Dialog to update the folder of a resource
 * If the resource was generated by an experiment, it updates the folder of the experiment if possible
 */
@Component({
  selector: 'lab-resource-update-folder-dialog',
  templateUrl: './lab-resource-update-folder-dialog.component.html',
  styleUrls: ['./lab-resource-update-folder-dialog.component.scss']
})
export class LabResourceUpdateFolderDialogComponent implements OnInit {

  formControl: FormControl<LabFolder>;

  isLoading: boolean;

  constructor(@Inject(MAT_DIALOG_DATA) public data: LabResourceUpdateFolderDialogInput,
              private dialogRef: MatDialogRef<LabResourceUpdateFolderDialogComponent>,
              private resourceService: LabResourceService,
              private experimentService: LabExperimentService,
              private snackBarService: FlSnackBarService) {
  }

  ngOnInit(): void {
    this.formControl = new FormControl(this.data.folder);
  }

  get isUpdateResourceFolderMode(): boolean {
    return !this.data.experiment;
  }

  submit(): void {
    if (this.formControl.valid && !this.isLoading) {
      this.isLoading = true;

      const folderId = this.formControl.value?.id ?? null;
      if (this.isUpdateResourceFolderMode) {
        this.updateResourceFolder(folderId);
      } else {
        this.updateExperimentFolder(folderId);
      }
    }
  }

  private updateResourceFolder(folderId: string): void {
    this.resourceService.updateFolder(this.data.resourceId, folderId).subscribe({
      next: resource => this.updateResourceFolderSuccess(resource),
      error: () => this.isLoading = false
    });
  }

  private updateResourceFolderSuccess(resource: LabResource): void {
    this.snackBarService.openSuccessMessage({text: 'biox.resource_folder_updated', translateText: true});
    this.closeDialog(resource.folder);
  }

  private updateExperimentFolder(folderId: string): void {
    this.experimentService.updateFolder(this.data.experiment.id, folderId).subscribe({
      next: experiment => this.updateExperimentFolderSuccess(experiment),
      error: () => this.isLoading = false
    });
  }

  private updateExperimentFolderSuccess(experiment: LabExperiment): void {
    this.snackBarService.openSuccessMessage({text: 'biox.experiment_folder_updated', translateText: true});
    this.closeDialog(experiment.folder);
  }

  private closeDialog(folder: LabFolder): void {
    this.isLoading = false;
    this.dialogRef.close({folder: folder} as LabResourceUpdateFolderDialogOutput);
  }


}
