import {
  Component,
  ElementRef,
  HostBinding,
  inject,
  Input,
  OnInit,
  SecurityContext,
  TemplateRef,
  ViewChild,
} from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import { ClHelpService } from '@monorepo/core-lib';
import { FlInputFileDirective } from '@monorepo/front-core-lib/fl-input-file';
import { FlResizeEvent } from '@monorepo/front-core-lib/fl-resize';
import { Observable, of } from 'rxjs';

import { TeFigureBlockConfig } from '../../block/te-figure-block.class';
import { TeBlockFigureData, TeBlockFigureUploadedResponse } from '../../model/lib';
import { TeElementBlockDirective } from '../../model/te-element.directive';

/**
 * Figure component in text editor generated by {@link TeFigureBlock}
 */
@Component({
  selector: 'te-figure',
  templateUrl: './te-figure.component.html',
  styleUrls: ['./te-figure.component.scss'],
  standalone: false,
})
export class TeFigureComponent extends TeElementBlockDirective implements OnInit {
  private sanitizer = inject(DomSanitizer);
  private elementRef = inject<ElementRef<HTMLElement>>(ElementRef);

  @Input() data: TeBlockFigureData;

  @Input() config: TeFigureBlockConfig;

  @ViewChild('figure') figure: ElementRef<HTMLElement>;

  @ViewChild('templatePortalContent') templatePortalContent: TemplateRef<unknown>;

  @ViewChild(FlInputFileDirective, { read: ElementRef, static: false })
  inputFile: ElementRef<HTMLInputElement>;

  @HostBinding('attr.contenteditable') contenteditable = 'false';

  imageWidth: number;
  imageHeight: number;

  sanitizedUrl: string;

  imageReady = false;

  disabled$: Observable<boolean>;

  uploadIsLoading = false;

  constructor() {
    super();
  }

  ngOnInit(): void {
    if (!ClHelpService.isNullOrEmpty(this.data)) {
      // let the parent have its width
      setTimeout(() => this.initImage(this.data), 0);
    }

    this.disabled$ = of(this.disabled);

    // if the figure is empty, open the file selector
    // useful for case where figure block is added programmatically
    if (!this.disabled && !this.uploadIsLoading && this.newElement) {
      this.openFileSelector();
    }
  }

  private initImage(data: TeBlockFigureData): void {
    const imageUrl = this.config.getImageUrl(data.filename);
    this.sanitizedUrl = this.sanitizer.sanitize(SecurityContext.URL, imageUrl);

    const parentWidth = this.elementRef.nativeElement.clientWidth;
    // if the image is larger than container, resize it
    if (parentWidth > 0 && data.width > parentWidth) {
      this.imageWidth = parentWidth;
      this.imageHeight = (parentWidth / data.width) * data.height;
    } else {
      this.imageWidth = data.width;
      this.imageHeight = data.height;
    }

    this.imageReady = true;
  }

  onImageResize(resizeEvent: FlResizeEvent): void {
    this.data.width = resizeEvent.width;
    this.data.height = resizeEvent.height;
  }

  private openFileSelector(): void {
    setTimeout(() => this.inputFile.nativeElement.click(), 0);
  }

  public onFileSelected(file: File): void {
    this.uploadIsLoading = true;
    this.config.imageUploader(file).subscribe({
      next: (response) => this.onUploadSuccess(response),
      error: () => (this.uploadIsLoading = false),
    });
  }

  private onUploadSuccess(response: TeBlockFigureUploadedResponse): void {
    this.data = {
      filename: response.filename,
      width: response.width,
      height: response.height,
      naturalHeight: response.height,
      naturalWidth: response.width,
      title: '',
      caption: '',
    };
    this.initImage(this.data);
    this.uploadIsLoading = false;
  }
}
