import {Component, ElementRef, Input, OnInit, SecurityContext, TemplateRef, ViewChild} from '@angular/core';
import {DomSanitizer} from '@angular/platform-browser';
import {TeElementDirective} from '../../model/te-element.directive';
import {FlInputFileDirective, FlResizeEvent} from '@monorepo/front-core-lib';
import {Observable, of} from 'rxjs';
import {TeFigureBlockConfig, TeFigureBlockData, TeUploadedImage} from '../../block/te-figure-block.class';
import {ClHelpService} from '@monorepo/core-lib';

/**
 * Figure component in text editor generated by {@link FlTextEditorFigureBlot}
 */
@Component({
  selector: 'te-figure',
  templateUrl: './te-figure.component.html',
  styleUrls: ['./te-figure.component.scss']
})
export class TeFigureComponent extends TeElementDirective implements OnInit {

  @Input() data: TeFigureBlockData;

  @Input() config: TeFigureBlockConfig;

  @ViewChild('figure') figure: ElementRef<HTMLElement>;

  @ViewChild('templatePortalContent') templatePortalContent: TemplateRef<unknown>;

  @ViewChild(FlInputFileDirective, {read: ElementRef, static: false}) inputFile: ElementRef<HTMLInputElement>;

  imageWidth: number;
  imageHeight: number;

  sanitizedUrl: string;

  imageReady = false;

  disabled$: Observable<boolean>;

  uploadIsLoading = false;

  constructor(private sanitizer: DomSanitizer,
              private elementRef: ElementRef<HTMLElement>) {
    super();
  }

  ngOnInit(): void {
    if (!ClHelpService.isNullOrEmpty(this.data)) {
      // let the parent have its width
      setTimeout(() => this.initImage(this.data), 0);
    }

    this.disabled$ = of(this.disabled);
  }

  private initImage(data: TeFigureBlockData): void {
    const imageUrl = this.config.getImageUrl(data.filename);
    this.sanitizedUrl = this.sanitizer.sanitize(SecurityContext.URL, imageUrl);

    const parentWidth = this.elementRef.nativeElement.clientWidth;
    // if the image is larger than container, resize it
    if (parentWidth > 0 && data.width > parentWidth) {
      this.imageWidth = parentWidth;
      this.imageHeight = ((parentWidth / data.width) * data.height);
    } else {
      this.imageWidth = data.width;
      this.imageHeight = data.height;
    }

    this.imageReady = true;
  }

  onImageResize(resizeEvent: FlResizeEvent): void {
    this.data.width = resizeEvent.width;
    this.data.height = resizeEvent.height;
  }

  public openFileSelector(): void {
    setTimeout(() => this.inputFile.nativeElement.click(), 0);
  }

  public onFileSelected(file: File): void {
    this.uploadIsLoading = true;
    this.config.imageUploader(file).subscribe({
      next: (response) => this.onUploadSuccess(response),
      error: () => this.uploadIsLoading = false,
    });
  }

  private onUploadSuccess(response: TeUploadedImage): void {
    this.data = {
      filename: response.filename,
      width: response.width,
      height: response.height,
      naturalHeight: response.height,
      naturalWidth: response.width,
      title: '',
      caption: '',
    };
    this.initImage(this.data);
    this.uploadIsLoading = false;
  }

}
