import {
  Component,
  ElementRef,
  HostBinding,
  inject,
  Input,
  OnInit,
  SecurityContext,
  TemplateRef,
  ViewChild,
} from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import { ClHelpService } from '@monorepo/core-lib';
import { FlInputFileDirective } from '@monorepo/front-core-lib/fl-input-file';
import { FlResizeEvent } from '@monorepo/front-core-lib/fl-resize';
import { Observable, of } from 'rxjs';

import { TeFigureBlockConfig } from '../../block/te-figure-block.class';
import { TeBlockFigureData, TeBlockFigureUploadedResponse } from '../../model/lib';
import { TeElementBlockDirective } from '../../model/te-element.directive';
import { TeSourceUrlRegistry } from '../../model/te-source-url-registry';

/**
 * Figure component in text editor generated by {@link TeFigureBlock}
 */
@Component({
  selector: 'te-figure',
  templateUrl: './te-figure.component.html',
  styleUrls: ['./te-figure.component.scss'],
  standalone: false,
})
export class TeFigureComponent extends TeElementBlockDirective implements OnInit {
  private sanitizer = inject(DomSanitizer);
  private elementRef = inject<ElementRef<HTMLElement>>(ElementRef);

  @Input() data: TeBlockFigureData;

  @Input() config: TeFigureBlockConfig;

  @ViewChild('figure') figure: ElementRef<HTMLElement>;

  @ViewChild('templatePortalContent') templatePortalContent: TemplateRef<unknown>;

  @ViewChild(FlInputFileDirective, { read: ElementRef, static: false })
  inputFile: ElementRef<HTMLInputElement>;

  @HostBinding('attr.contenteditable') contenteditable = 'false';

  imageWidth: number;
  imageHeight: number;

  sanitizedUrl: string;

  imageReady = false;

  disabled$: Observable<boolean>;

  uploadIsLoading = false;

  /**
   * Source URL from another document, looked up from the registry during init.
   * Used to re-download and re-upload the image if it fails to load from the current document.
   */
  private sourceUrl: string | null = null;

  constructor() {
    super();
  }

  ngOnInit(): void {
    if (!ClHelpService.isNullOrEmpty(this.data)) {
      // Check if a source URL was registered for this filename (cross-document paste)
      this.sourceUrl = TeSourceUrlRegistry.consume(this.data.filename);

      // let the parent have its width
      setTimeout(() => this.initImage(this.data), 0);
    }

    this.disabled$ = of(this.disabled);

    // if the figure is empty, open the file selector
    // useful for case where figure block is added programmatically
    if (!this.disabled && !this.uploadIsLoading && this.newElement) {
      this.openFileSelector();
    }
  }

  private initImage(data: TeBlockFigureData): void {
    const imageUrl = this.config.getImageUrl(data.filename);
    this.sanitizedUrl = this.sanitizer.sanitize(SecurityContext.URL, imageUrl);

    // Set source URL attributes for cross-document copy support
    this.elementRef.nativeElement.setAttribute(TeSourceUrlRegistry.SOURCE_URL_ATTR, this.sanitizedUrl);
    this.elementRef.nativeElement.setAttribute(TeSourceUrlRegistry.SOURCE_FILENAME_ATTR, data.filename);

    const parentWidth = this.elementRef.nativeElement.clientWidth;
    // if the image is larger than container, resize it
    if (parentWidth > 0 && data.width > parentWidth) {
      this.imageWidth = parentWidth;
      this.imageHeight = (parentWidth / data.width) * data.height;
    } else {
      this.imageWidth = data.width;
      this.imageHeight = data.height;
    }

    this.imageReady = true;
  }

  onImageResize(resizeEvent: FlResizeEvent): void {
    this.data.width = resizeEvent.width;
    this.data.height = resizeEvent.height;
  }

  /**
   * Called when the image fails to load (e.g. cross-document paste where the filename
   * references an image in another document). If a source URL is available,
   * download the image from the source and re-upload it to the current document.
   */
  onImageLoadError(): void {
    if (!this.sourceUrl || this.disabled || this.uploadIsLoading) return;

    const url = this.sourceUrl;
    this.sourceUrl = null; // prevent retry loop
    this.imageReady = false;
    this.uploadIsLoading = true;

    fetch(url, { credentials: 'include' })
      .then((response) => {
        if (!response.ok) throw new Error(`Failed to fetch image: ${response.status}`);
        return response.blob();
      })
      .then((blob) => {
        const extension = blob.type.split('/')[1] || 'png';
        const file = new File([blob], `pasted-image.${extension}`, { type: blob.type });
        this.onFileSelected(file);
      })
      .catch(() => {
        this.uploadIsLoading = false;
      });
  }

  private openFileSelector(): void {
    setTimeout(() => this.inputFile.nativeElement.click(), 0);
  }

  public onFileSelected(file: File): void {
    this.uploadIsLoading = true;
    this.config.imageUploader(file).subscribe({
      next: (response) => this.onUploadSuccess(response),
      error: () => (this.uploadIsLoading = false),
    });
  }

  private onUploadSuccess(response: TeBlockFigureUploadedResponse): void {
    this.data = {
      filename: response.filename,
      width: response.width,
      height: response.height,
      naturalHeight: response.height,
      naturalWidth: response.width,
      title: '',
      caption: '',
    };
    this.initImage(this.data);
    this.uploadIsLoading = false;
  }
}
