server {
      listen 81;
      server_name gencovery.com;

      # Point to index.html
      root   /usr/share/nginx/html;
      index  index.html index.htm;

      # keep the normal behavior for the css theme and json files (translations)
      # not cachable because of the file names don't change on a new version
      location ~ (dark-theme\.css|light-theme\.css|\.json)$ {
        add_header Cache-Control "no-store";
        try_files $uri $uri/ /index.html;
      }

      # don't cache the index.html
      # set all rules here because this is the entry point of the app

      location ~ \.(html)$ {
        add_header Cache-Control "no-store";
        add_header X-Frame-Options "SAMEORIGIN";

        # Security header configuration
        add_header Cache-Control no-cache;
        # add_header X-Frame-Options "DENY";
        add_header X-Content-Type-Options nosniff;
        add_header X-Xss-Protection "1; mode=block" always;

        # CSP FOR LOCAL ENV contains localhost:3001 in src
        # DO NOT COMMIT THIS LINE UNCOMMENTED
        # add_header Content-Security-Policy "default-src 'self' 'unsafe-eval' localhost:3001; script-src-elem 'self' localhost:3001 data:; frame-src 'self' *.gencovery.io *.constellab.app https://www.google.com; worker-src  data: 'self' blob:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: http: https: ; font-src 'self' data: http: https: fonts.googleapis.com; connect-src 'self' https://fonts.googleapis.com localhost:*;";

        # CSP FOR PROD ENV
        # localhost:* is for desktop lab
        set $DEFAULT_SRC "default-src 'self' *.gencovery.io *.constellab.app *.preconstellab.com *.constellab.space *.gencovery.com localhost:*";
        # script-src : https://www.google.com, https://www.gstatic.com
        set $SCRIPT_SRC_ELEM "script-src-elem 'self' *.gencovery.io *.constellab.app *.preconstellab.com *.constellab.space *.gencovery.com localhost:* https://www.google.com https://www.gstatic.com data:";
        #frame-src https://www.google.com is for the recaptcha
        set $FRAME_SRC "frame-src 'self' youtube.com www.youtube.com https://www.google.com";
        set $WORKER_SRC "worker-src  *.gencovery.io *.constellab.app *.preconstellab.com *.constellab.space localhost:* data: 'self' blob:";
        set $STYLE_SRC "style-src 'self' 'unsafe-inline'  *.gencovery.io *.constellab.app *.preconstellab.com *.constellab.space *.gencovery.com localhost:* https://fonts.googleapis.com";
        set $IMG_SRC "img-src 'self' blob: data: http: https:  *.gencovery.io *.constellab.app *.preconstellab.com *.constellab.space *.gencovery.com localhost:*";
        set $FONT_SRC "font-src 'self' data: http: https: fonts.googleapis.com";
        set $CONNECT_SRC "connect-src 'self'  *.gencovery.io *.constellab.app *.preconstellab.com *.constellab.space *.gencovery.com localhost:* https://fonts.googleapis.com https://fonts.gstatic.com";
        add_header Content-Security-Policy "${DEFAULT_SRC}; ${SCRIPT_SRC_ELEM}; ${FRAME_SRC}; ${WORKER_SRC}; ${STYLE_SRC}; ${IMG_SRC}; ${FONT_SRC}; ${CONNECT_SRC};";

        add_header Referrer-Policy "no-referrer-when-downgrade";
        add_header Feature-Policy "accelerometer 'none'; autoplay 'none'; camera 'none' encrypted-media 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; speaker 'none'; vr 'none'; vibrate 'none'";

        try_files $uri $uri/ /index.html;
      }

      # cache all the css, js and ttf files for a weak
      location ~ \.(css|js|ttf)$ {
        # Cache duration : 1 week
        expires 604800;
        add_header Cache-Control "max-age=604800, public";
        try_files $uri $uri/ /index.html;
      }


      location / {
          try_files $uri $uri/ /index.html;
      }
}
