import { Component, EventEmitter, OnInit, Output, inject } from '@angular/core';
import {
  CaServerDecisionTreeDTO,
  CaServerDecisionTreeOptionDTO,
} from '../../../../model/entities/server/ca-server-standard.class';
import { MatRadioChange, MatRadioGroup, MatRadioButton } from '@angular/material/radio';
import { CaSettingsService } from '../../../../service-api/ca-settings.service';
import { FlSectionModule } from '@monorepo/front-core-lib/fl-section';
import { FlRadioButtonBigModule } from '@monorepo/front-core-lib/fl-radio-button-big';

export interface CaServerDecisionTreeOptionFlatDTO {
  id: number;
  title: string;
  description: string;

  level: number;
  suggestedServerNames?: string[];
  parentId: number | null;
}

@Component({
  selector: 'ca-server-decision-tree',
  templateUrl: './ca-server-decision-tree.component.html',
  styleUrl: './ca-server-decision-tree.component.scss',
  imports: [FlSectionModule, MatRadioGroup, MatRadioButton, FlRadioButtonBigModule],
})
export class CaServerDecisionTreeComponent implements OnInit {
  private settingsService = inject(CaSettingsService);

  /**
   * Emit all the standard server names generated by the decision tree
   */
  @Output() standardServerChanged: EventEmitter<string[]> = new EventEmitter();

  flatOptions: CaServerDecisionTreeOptionFlatDTO[];
  displayedOptions: CaServerDecisionTreeOptionFlatDTO[][];

  isLoading: boolean;

  private flatId: number = 0;

  ngOnInit(): void {
    this.isLoading = true;
    this.settingsService.getDecisionTree().subscribe({
      next: (decisionTree) => this.getDecisionTreeSuccess(decisionTree),
      error: () => (this.isLoading = false),
    });
  }

  private getDecisionTreeSuccess(decisionTree: CaServerDecisionTreeDTO): void {
    // init options
    this.flatOptions = this.toFlatOptions(decisionTree.tree, [], 0, -1);
    this.displayedOptions = [this.getFlatOptionsByParentId(-1)];
    this.isLoading = false;
  }

  selectOption(change: MatRadioChange): void {
    const option: CaServerDecisionTreeOptionFlatDTO = change.value;

    // clear all the next levels (if a previous option was selected)
    this.displayedOptions = this.displayedOptions.slice(0, option.level + 1);

    if (option.suggestedServerNames) {
      this.standardServerChanged.emit(option.suggestedServerNames);
    } else {
      this.standardServerChanged.emit(null);

      // add the next level
      const nextOptions = this.getFlatOptionsByParentId(option.id);
      this.displayedOptions.push(nextOptions);
    }
  }

  private getFlatOptionsByParentId(parentId: number): CaServerDecisionTreeOptionFlatDTO[] {
    return this.flatOptions.filter((option) => option.parentId === parentId);
  }

  private toFlatOptions(
    options: CaServerDecisionTreeOptionDTO[],
    flatOptions: CaServerDecisionTreeOptionFlatDTO[],
    level: number,
    parentId: number
  ): CaServerDecisionTreeOptionFlatDTO[] {
    for (const option of options) {
      const flatOption: CaServerDecisionTreeOptionFlatDTO = {
        id: this.flatId++,
        title: option.title,
        description: option.description,
        level,
        suggestedServerNames: option.suggestedServerNames,
        parentId,
      };
      flatOptions.push(flatOption);
      if (option.children) {
        this.toFlatOptions(option.children, flatOptions, level + 1, flatOption.id);
      }
    }

    return flatOptions;
  }
}
