import { ClNumberHelper, ClStringHelper } from '@monorepo/core-lib';

export type ChChartLabelFormatFunction = (domainValue: number, index: number) => string;

export class ChChartLabelFormatter {
  // max length of the label generated by the short format function
  public static readonly defaultFormatNumberShortMaxLength = 7;

  /**
   * Format the label base on the format function
   * @param shortFormat the format function for the short label
   * @param shortFormatMaxLength the max length of the label generated by the short format function
   * (use to anticipate the space needed)
   * @param longFormat the format function for the long label
   */
  constructor(
    private shortFormat: ChChartLabelFormatFunction,
    public shortFormatMaxLength: number,
    private longFormat: ChChartLabelFormatFunction = shortFormat
  ) {}

  /**
   * Create the format function for the axis from a list of label
   * It considers the value as index and pick the label at this index
   * @param tickLabels
   */
  public static fromTickLabels(tickLabels: string[]): ChChartLabelFormatter {
    return new ChChartLabelFormatter(
      (value) => tickLabels[value] ?? value.toString(),
      tickLabels.reduce((p, c) => Math.max(p, c?.toString()?.length ?? 0), 0)
    );
  }

  /**
   * Convert a number to a string using scientific notation for number > 10000 or < 0.0001
   * With this the max label length is 7 because the number are displayed with 4 digits after the
   * commas (ex: 1.2345)
   *  or in scientific notation with 2 digit after the commas (ex: 1.23e+5)
   */
  public static getDefaultTickLabel(): ChChartLabelFormatter {
    const format: ChChartLabelFormatFunction = (num: number) => this.formatNumberShort(num);

    return new ChChartLabelFormatter(format, ChChartLabelFormatter.defaultFormatNumberShortMaxLength, (d) =>
      d?.toString()
    );
  }

  /**
   * Convert a number to a string using scientific notation for number > 10000 or < 0.0001
   * With this the max label length is 7 because the number are displayed with 4 digits after the
   * commas (ex: 1.2345)
   *  or in scientific notation with 2 digit after the commas (ex: 1.23e+5)
   */
  public static formatNumberShort(num: number): string {
    if (num == null) return 'null';
    if (num === 0) return '0';
    const precision: number = 4;
    if (Math.abs(num) > 10 ** precision || Math.abs(num) < 10 ** -precision) {
      return num.toExponential(2);
    } else {
      return ClNumberHelper.round(num, precision).toString();
    }
  }

  /**
   * Format the lab base on the format function
   * @param domainValue
   * @param index the index of the domain value, can be null
   * @param maxLength truncate the label to this length
   */
  public formatShort(domainValue: number, index: number = null, maxLength: number = null): string {
    const label = this.shortFormat(domainValue, index);
    if (maxLength) {
      return ClStringHelper.limiteLength(label, maxLength);
    }
    return label;
  }

  public formatLong(domainValue: number): string {
    return this.longFormat(domainValue, null);
  }
}
