import { Component, OnInit, inject } from '@angular/core';
import { FlDialogModule } from '@monorepo/front-core-lib/fl-dialog';
import { FlLoaderModule } from '@monorepo/front-core-lib/fl-loader';
import { FlSnackBarService } from '@monorepo/front-core-lib/fl-snack-bar';
import { FormControl, FormsModule, ReactiveFormsModule } from '@angular/forms';
import {
  LiFolder,
  LiResource,
  LiResourceService,
  LiScenario,
  LiScenarioService,
} from '@monorepo/lab-lib/li-core';
import { LiFolderSelectComponent } from '@monorepo/lab-lib/li-folder';
import { MAT_DIALOG_DATA, MatDialogActions, MatDialogContent, MatDialogRef } from '@angular/material/dialog';
import { MatButton } from '@angular/material/button';
import { TranslatePipe } from '@ngx-translate/core';

export interface LiResourceUpdateFolderDialogInput {
  resourceId: string;
  scenario?: {
    id: string;
    title: string;
  };
  folder?: LiFolder;
}

export interface LiResourceUpdateFolderDialogOutput {
  folder?: LiFolder;
}

/**
 * Dialog to update the folder of a resource
 * If the resource was generated by a scenario, it updates the folder of the scenario if possible
 */
@Component({
  selector: 'li-resource-update-folder-dialog',
  templateUrl: './li-resource-update-folder-dialog.component.html',
  styleUrls: ['./li-resource-update-folder-dialog.component.scss'],
  imports: [
    FlDialogModule,
    MatDialogContent,
    ReactiveFormsModule,
    FormsModule,
    LiFolderSelectComponent,
    MatDialogActions,
    MatButton,
    FlLoaderModule,
    TranslatePipe,
  ],
})
export class LiResourceUpdateFolderDialogComponent implements OnInit {
  data = inject<LiResourceUpdateFolderDialogInput>(MAT_DIALOG_DATA);
  private dialogRef = inject<MatDialogRef<LiResourceUpdateFolderDialogComponent>>(MatDialogRef);
  private resourceService = inject(LiResourceService);
  private scenarioService = inject(LiScenarioService);
  private snackBarService = inject(FlSnackBarService);

  formControl: FormControl<LiFolder>;

  isLoading: boolean;

  ngOnInit(): void {
    this.formControl = new FormControl(this.data.folder);
  }

  get isUpdateResourceFolderMode(): boolean {
    return !this.data.scenario;
  }

  submit(): void {
    if (this.formControl.valid && !this.isLoading) {
      this.isLoading = true;

      const folderId = this.formControl.value?.id ?? null;
      if (this.isUpdateResourceFolderMode) {
        this.updateResourceFolder(folderId);
      } else {
        this.updateScenarioFolder(folderId);
      }
    }
  }

  private updateResourceFolder(folderId: string): void {
    this.resourceService.updateFolder(this.data.resourceId, folderId).subscribe({
      next: (resource) => this.updateResourceFolderSuccess(resource),
      error: () => (this.isLoading = false),
    });
  }

  private updateResourceFolderSuccess(resource: LiResource): void {
    this.snackBarService.openSuccessMessage({ text: 'biox.resource_folder_updated', translateText: true });
    this.closeDialog(resource.folder);
  }

  private updateScenarioFolder(folderId: string): void {
    this.scenarioService.updateFolder(this.data.scenario.id, folderId).subscribe({
      next: (scenario) => this.updateScenarioFolderSuccess(scenario),
      error: () => (this.isLoading = false),
    });
  }

  private updateScenarioFolderSuccess(scenario: LiScenario): void {
    this.snackBarService.openSuccessMessage({ text: 'biox.scenario_folder_updated', translateText: true });
    this.closeDialog(scenario.folder);
  }

  private closeDialog(folder: LiFolder): void {
    this.isLoading = false;
    this.dialogRef.close({ folder: folder } as LiResourceUpdateFolderDialogOutput);
  }
}
