/**
 * File that group all the base routes for the modules
 */
export const LI_CONST_BASE_ROUTE = 'app';

export const LI_CONST_SCENARIO_ROUTE = 'scenario';
export const LI_CONST_BIOTA_ROUTE = 'biota';
export const LI_CONST_RESOURCE_ROUTE = 'resource';
export const LI_CONST_APP_ROUTE = 'app';
export const LI_CONST_NOTE_ROUTE = 'note';
export const LI_CONST_VIEW_ROUTE = 'view';
export const LI_CONST_MONITORING_ROUTE = 'monitoring';
export const LI_CONST_DOC_ROUTE = 'doc';
export const LI_CONST_SCENARIO_TEMPLATE_ROUTE = 'scenario-template';
export const LI_CONST_NOTE_TEMPLATE_ROUTE = 'note-template';
export const LI_CONST_OPEN_ROUTE = 'open';
export const LI_CONST_TAG_ROUTE = 'tag';
export const LI_CONST_LOGIN_ROUTE = '/login';

export const LI_CONST_SCENARIO_FULL_ROUTE = `/${LI_CONST_BASE_ROUTE}/${LI_CONST_SCENARIO_ROUTE}`;
export const LI_CONST_BIOTA_FULL_ROUTE = `/${LI_CONST_BASE_ROUTE}/${LI_CONST_BIOTA_ROUTE}`;
export const LI_CONST_RESOURCE_FULL_ROUTE = `/${LI_CONST_BASE_ROUTE}/${LI_CONST_RESOURCE_ROUTE}`;
export const LI_CONST_APP_FULL_ROUTE = `/${LI_CONST_BASE_ROUTE}/${LI_CONST_APP_ROUTE}`;
export const LI_CONST_NOTE_FULL_ROUTE = `/${LI_CONST_BASE_ROUTE}/${LI_CONST_NOTE_ROUTE}`;
export const LI_CONST_VIEW_FULL_ROUTE = `/${LI_CONST_BASE_ROUTE}/${LI_CONST_VIEW_ROUTE}`;
export const LI_CONST_MONITORING_FULL_ROUTE = `/${LI_CONST_BASE_ROUTE}/${LI_CONST_MONITORING_ROUTE}`;
export const LI_CONST_DOC_FULL_ROUTE = `/${LI_CONST_BASE_ROUTE}/${LI_CONST_DOC_ROUTE}`;
export const LI_CONST_SCENARIO_TEMPLATE_FULL_ROUTE =
  `/${LI_CONST_BASE_ROUTE}/` + LI_CONST_SCENARIO_TEMPLATE_ROUTE;
export const LI_CONST_NOTE_TEMPLATE_FULL_ROUTE = `/${LI_CONST_BASE_ROUTE}/` + LI_CONST_NOTE_TEMPLATE_ROUTE;
export const LI_CONST_TAG_FULL_ROUTE = `/${LI_CONST_BASE_ROUTE}/${LI_CONST_TAG_ROUTE}`;

export const LI_CONST_FORM_ROUTE = 'form';
export const LI_CONST_FORM_FULL_ROUTE = `/${LI_CONST_BASE_ROUTE}/${LI_CONST_FORM_ROUTE}`;
export const LI_CONST_FORM_TEMPLATE_ROUTE = 'form-template';
export const LI_CONST_FORM_TEMPLATE_FULL_ROUTE = `/${LI_CONST_BASE_ROUTE}/${LI_CONST_FORM_TEMPLATE_ROUTE}`;
