import {Component, Inject, OnInit} from '@angular/core';
import {LabProject} from '../../../../model/entities/lab-project.class';
import {MAT_DIALOG_DATA, MatDialogRef} from '@angular/material/dialog';
import {LabResourceService} from '../../../../entity-service/lab-resource.service';
import {LabExperimentService} from '../../../../entity-service/lab-experiment.service';
import {FormControl} from '@angular/forms';
import {FlSnackBarService} from '@monorepo/front-core-lib';
import {LabExperiment} from '../../../../model/entities/lab-experiment.entity';
import {LabResource} from '../../../../model/entities/resource/lab-resource.entity';


export interface LabResourceUpdateProjectDialogInput {
  resourceId: string;
  experiment?: {
    id: string;
    title: string;
  };
  project?: LabProject;
}

export interface LabResourceUpdateProjectDialogOutput {
  project?: LabProject;
}

/**
 * Dialog to update the project of a resource
 * If the resource was generated by an experiment, it updates the project of the experiment if possible
 */
@Component({
  selector: 'lab-resource-update-project-dialog',
  templateUrl: './lab-resource-update-project-dialog.component.html',
  styleUrls: ['./lab-resource-update-project-dialog.component.scss']
})
export class LabResourceUpdateProjectDialogComponent implements OnInit {

  formControl: FormControl<LabProject>;

  isLoading: boolean;

  constructor(@Inject(MAT_DIALOG_DATA) public data: LabResourceUpdateProjectDialogInput,
              private dialogRef: MatDialogRef<LabResourceUpdateProjectDialogComponent>,
              private resourceService: LabResourceService,
              private experimentService: LabExperimentService,
              private snackBarService: FlSnackBarService) {
  }

  ngOnInit(): void {
    this.formControl = new FormControl(this.data.project);
  }

  get isUpdateResourceProjectMode(): boolean {
    return !this.data.experiment;
  }

  submit(): void {
    if (this.formControl.valid && !this.isLoading) {
      this.isLoading = true;

      const projectId = this.formControl.value?.id ?? null;
      if (this.isUpdateResourceProjectMode) {
        this.updateResourceProject(projectId);
      } else {
        this.updateExperimentProject(projectId);
      }
    }
  }

  private updateResourceProject(projectId: string): void {
    this.resourceService.updateProject(this.data.resourceId, projectId).subscribe({
      next: resource => this.updateResourceProjectSuccess(resource),
      error: () => this.isLoading = false
    });
  }

  private updateResourceProjectSuccess(resource: LabResource): void {
    this.snackBarService.openSuccessMessage({text: 'biox.resource_project_updated', translateText: true});
    this.closeDialog(resource.project);
  }

  private updateExperimentProject(projectId: string): void {
    this.experimentService.updateProject(this.data.experiment.id, projectId).subscribe({
      next: experiment => this.updateExperimentProjectSuccess(experiment),
      error: () => this.isLoading = false
    });
  }

  private updateExperimentProjectSuccess(experiment: LabExperiment): void {
    this.snackBarService.openSuccessMessage({text: 'biox.experiment_project_updated', translateText: true});
    this.closeDialog(experiment.project);
  }

  private closeDialog(project: LabProject): void {
    this.isLoading = false;
    this.dialogRef.close({project: project} as LabResourceUpdateProjectDialogOutput);
  }


}
