export class FlColorHelper {
  public static readonly blue = 'rgba(29,123,195,1)';
  public static readonly pinkShiny = 'rgba(255,0,135,1)';
  public static readonly green = 'rgba(35,152,13,1)';
  public static readonly yellow = 'rgba(251,209,39,1)';
  public static readonly purple = 'rgba(140,13,164,1)';
  public static readonly lightBlue = 'rgba(140,227,230,1)';
  public static readonly palePink = 'rgba(231,124,159,1)';
  public static readonly paleGreen = 'rgba(123,155,71,1)';
  public static readonly orange = 'rgba(254,143,6,1)';
  public static readonly pink = 'rgba(239,102,240,1)';
  public static readonly brown = 'rgba(153,92,27,1)';
  public static readonly blueGreen = 'rgba(17,160,170,1)';
  public static readonly darkBlue = 'rgba(79,66,171,1)';
  public static readonly red = 'rgba(231,37,37,1)';
  public static readonly darkGreen = 'rgba(38,92,66,1)';
  public static readonly beige = 'rgba(210,160,136,1)';
  public static readonly lightGreen = 'rgba(187,226,114,1)';
  public static readonly mallow = 'rgba(171,43,96,1)';
  public static readonly greenShiny = 'rgba(83,224,120,1)';
  public static readonly grey = 'rgba(90,80,82,1)';
  public static readonly blueGrey = 'rgba(162,184,240,1)';
  public static readonly palePurple = 'rgba(158,126,233,1)';

  public static transparentBlack = 'rgba(0,0,0,0.5)';

  // color for color blind : https://jfly.uni-koeln.de/color/
  // return ['rgba(230,159,0,1)', 'rgba(86,180,233,1)', 'rgba(0,158,115,1)', 'rgba(240,228,66,1)',
  //   'rgba(0,114,178,1)', 'rgba(213,92,0,1)', 'rgba(204,121,167,1)'];

  /**
   * return hexa color base generated by string with #
   */
  public static stringToRGBColor(str: string): string {
    return '#' + FlColorHelper.stringToRGB(str);
  }

  /**
   * return hexa color base generated by string
   */
  public static stringToRGB(str: string): string {
    return FlColorHelper.intToRGB(FlColorHelper.hashCode(str));
  }

  /**
   * return hexa color base generated by int
   */
  public static intToRGB(i: number): string {
    const c = (i & 0x00ffffff).toString(16).toUpperCase();

    return '00000'.substring(0, 6 - c.length) + c;
  }

  // get hash form string
  private static hashCode(str: string): number {
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
      hash = str.charCodeAt(i) + ((hash << 5) - hash);
    }
    return hash;
  }

  // return a list of colors
  public static getColorList(transparencyAlpha: number = 1): string[] {
    const colorList: string[] = [
      this.blue,
      this.pinkShiny,
      this.green,
      this.yellow,
      this.purple,
      this.lightBlue,
      this.palePink,
      this.paleGreen,
      this.orange,
      this.pink,
      this.brown,
      this.blueGreen,
      this.darkBlue,
      this.red,
      this.darkGreen,
      this.beige,
      this.lightGreen,
      this.mallow,
      this.greenShiny,
      this.grey,
      this.blueGrey,
      this.palePurple,
    ];
    if (transparencyAlpha === 1) {
      return colorList;
    }

    // change the transparency
    const colorListWithTransparency: string[] = [];
    for (const color of colorList) {
      colorListWithTransparency.push(color.replace('1)', `${transparencyAlpha})`));
    }

    return colorListWithTransparency;
  }

  public static getColorFromIndex(index: number): string {
    const colors = FlColorHelper.getColorList();

    return colors[index % colors.length];
  }

  public static getColorsGroups(): string[][] {
    // return [
    //   ['#ffcdd2', '#ef9a9a', '#e57373'],
    //   ['#bbdefb', '#90caf9', '#64b5f6'],
    //   ['#f0f4c3', '#e6ee9c', '#dce775'],
    // ]
    return [
      ['#4a148c', '#6a1b9a', '#7b1fa2'],
      ['#303f9f', '#283593', '#1a237e'],
      ['#00796b', '#00695c', '#004d40'],
    ];
  }

  /**
   * Get the contrasting color for any hex color
   * @param hexColor
   */
  public static getContrastColor(hexColor: string): string {
    // If a leading # is provided, remove it
    if (hexColor.slice(0, 1) === '#') {
      hexColor = hexColor.slice(1);
    }

    // If a three-character hexcode, make six-character
    if (hexColor.length === 3) {
      hexColor = hexColor
        .split('')
        .map(function (hex) {
          return hex + hex;
        })
        .join('');
    }

    // Convert to RGB value
    const r = parseInt(hexColor.substring(0, 2), 16);
    const g = parseInt(hexColor.substring(2, 4), 16);
    const b = parseInt(hexColor.substring(4, 6), 16);

    // Get YIQ ratio
    const yiq = (r * 299 + g * 587 + b * 114) / 1000;

    // Check contrast
    return yiq >= 128 ? 'black' : 'white';
  }
}
