name: Build streamlit components

on:
  push:
    tags:
      - 'dc_streamlit_components_*'

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/build-dashboard-components.yml
    with:
      app_name: streamlit-components
      github_ref: ${{ github.ref_name }}
    secrets:
      release_dashboard_components: ${{ secrets.RELEASE_DASHBOARD_COMPONENTS }}
