name: Main Workflow space front

on:
  push:
    tags:
      - "ca_*"

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/build_github_package.yml
    with:
      registry: ghcr.io
      image_name: ghcr.io/constellab/space-front
      github_ref: ${{ github.ref }}
      tag_prefix: ca_
      dockerfile_path: ./apps/ca-space-front/Dockerfile
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.GITHUB_TOKEN }}
